trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  sourceDirectory: $(System.DefaultWorkingDirectory)
  docusaurDirectory: docusaur

steps:
  - script: |
      find $(sourceDirectory)/$(docusaurDirectory) \(-type f -o -type d\) -name 'DRAFT*' -exec rm -rf {} +
    displayName: 'Remove draft files and directories.'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: $(docusaurDirectory)
      app_build_command: npm run build
      output_location: build
    env:
      azure_static_web_apps_api_token: $(swa_deployment_token)
