trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  workingDir: Build.ArtifactStagingDirectory
  docusaurDir: docusaur
  blogDir: blog
  docsDir: docs

steps:
  - script: ls $(workingDir)
    displayName: 'Check contents of workingDir'
  - script: |
      find $(workingDir)/$(docusaurDir) -type f -name 'DRAFT*' -exec rm {} +
      find $(workingDir)/$(docusaurDir) -type d -name 'DRAFT*' -exec rmdir {} +
    displayName: 'Remove draft files and directories.'
  - task: AzureStaticWebApp@0
    inputs:
      app_location: docusaur
      app_build_command: npm run build
      output_location: build
    env:
      azure_static_web_apps_api_token: $(swa_deployment_token)
